/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HelpRouteImport } from './routes/help'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SegurancaAdolescentesRouteImport } from './routes/seguranca-adolescentes'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedClipsRouteImport } from './routes/_authenticated/clips'
import { Route as AuthenticatedExplorarRouteImport } from './routes/_authenticated/explorar'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedNegociosRouteImport } from './routes/_authenticated/negocios'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedPublicarRouteImport } from './routes/_authenticated/publicar'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDenunciasRouteImport } from './routes/admin/denuncias'
import { Route as AdminNegociosRouteImport } from './routes/admin/negocios'
import { Route as AdminSuporteRouteImport } from './routes/admin/suporte'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as ComunidadesIndexRouteImport } from './routes/comunidades.index'
import { Route as ComunidadesNovaRouteImport } from './routes/comunidades.nova'
import { Route as HelpAccountRouteImport } from './routes/help.account'
import { Route as HelpAdsRouteImport } from './routes/help.ads'
import { Route as HelpBusinessRouteImport } from './routes/help.business'
import { Route as HelpChamadosRouteImport } from './routes/help.chamados'
import { Route as HelpCommunityRouteImport } from './routes/help.community'
import { Route as HelpMessagesRouteImport } from './routes/help.messages'
import { Route as HelpPostsRouteImport } from './routes/help.posts'
import { Route as HelpSecurityRouteImport } from './routes/help.security'
import { Route as HelpShopRouteImport } from './routes/help.shop'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as AuthenticatedConfiguracoesPerfilRouteImport } from './routes/_authenticated/configuracoes.perfil'
import { Route as AuthenticatedMensagensIndexRouteImport } from './routes/_authenticated/mensagens.index'
import { Route as AuthenticatedMensagensIdRouteImport } from './routes/_authenticated/mensagens.$id'
import { Route as HelpChamadosNovoRouteImport } from './routes/help.chamados.novo'
import { Route as AuthenticatedUUsernameAmigosRouteImport } from './routes/_authenticated/u.$username.amigos'
import { Route as AuthenticatedUUsernameSeguidoresRouteImport } from './routes/_authenticated/u.$username.seguidores'
import { Route as AuthenticatedUUsernameSeguindoRouteImport } from './routes/_authenticated/u.$username.seguindo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaAdolescentesRoute = SegurancaAdolescentesRouteImport.update({
  id: '/seguranca-adolescentes',
  path: '/seguranca-adolescentes',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClipsRoute = AuthenticatedClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExplorarRoute = AuthenticatedExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNegociosRoute = AuthenticatedNegociosRouteImport.update({
  id: '/negocios',
  path: '/negocios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPublicarRoute = AuthenticatedPublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDenunciasRoute = AdminDenunciasRouteImport.update({
  id: '/admin/denuncias',
  path: '/admin/denuncias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNegociosRoute = AdminNegociosRouteImport.update({
  id: '/admin/negocios',
  path: '/admin/negocios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/admin/suporte',
  path: '/admin/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadesIndexRoute = ComunidadesIndexRouteImport.update({
  id: '/comunidades/',
  path: '/comunidades/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadesNovaRoute = ComunidadesNovaRouteImport.update({
  id: '/comunidades/nova',
  path: '/comunidades/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpAccountRoute = HelpAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => HelpRoute,
} as any)
const HelpAdsRoute = HelpAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => HelpRoute,
} as any)
const HelpBusinessRoute = HelpBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => HelpRoute,
} as any)
const HelpChamadosRoute = HelpChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => HelpRoute,
} as any)
const HelpCommunityRoute = HelpCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => HelpRoute,
} as any)
const HelpMessagesRoute = HelpMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => HelpRoute,
} as any)
const HelpPostsRoute = HelpPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => HelpRoute,
} as any)
const HelpSecurityRoute = HelpSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => HelpRoute,
} as any)
const HelpShopRoute = HelpShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => HelpRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesPerfilRoute =
  AuthenticatedConfiguracoesPerfilRouteImport.update({
    id: '/configuracoes/perfil',
    path: '/configuracoes/perfil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMensagensIndexRoute =
  AuthenticatedMensagensIndexRouteImport.update({
    id: '/mensagens/',
    path: '/mensagens/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMensagensIdRoute =
  AuthenticatedMensagensIdRouteImport.update({
    id: '/mensagens/$id',
    path: '/mensagens/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const HelpChamadosNovoRoute = HelpChamadosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => HelpChamadosRoute,
} as any)
const AuthenticatedUUsernameAmigosRoute =
  AuthenticatedUUsernameAmigosRouteImport.update({
    id: '/u/$username/amigos',
    path: '/u/$username/amigos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUUsernameSeguidoresRoute =
  AuthenticatedUUsernameSeguidoresRouteImport.update({
    id: '/u/$username/seguidores',
    path: '/u/$username/seguidores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUUsernameSeguindoRoute =
  AuthenticatedUUsernameSeguindoRouteImport.update({
    id: '/u/$username/seguindo',
    path: '/u/$username/seguindo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seguranca-adolescentes': typeof SegurancaAdolescentesRoute
  '/termos': typeof TermosRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app': typeof AuthenticatedAppRoute
  '/clips': typeof AuthenticatedClipsRoute
  '/explorar': typeof AuthenticatedExplorarRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/negocios': typeof AuthenticatedNegociosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/publicar': typeof AuthenticatedPublicarRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/negocios': typeof AdminNegociosRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/c/$slug': typeof CSlugRoute
  '/comunidades/nova': typeof ComunidadesNovaRoute
  '/help/account': typeof HelpAccountRoute
  '/help/ads': typeof HelpAdsRoute
  '/help/business': typeof HelpBusinessRoute
  '/help/chamados': typeof HelpChamadosRouteWithChildren
  '/help/community': typeof HelpCommunityRoute
  '/help/messages': typeof HelpMessagesRoute
  '/help/posts': typeof HelpPostsRoute
  '/help/security': typeof HelpSecurityRoute
  '/help/shop': typeof HelpShopRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/comunidades/': typeof ComunidadesIndexRoute
  '/configuracoes/perfil': typeof AuthenticatedConfiguracoesPerfilRoute
  '/mensagens/$id': typeof AuthenticatedMensagensIdRoute
  '/help/chamados/novo': typeof HelpChamadosNovoRoute
  '/mensagens/': typeof AuthenticatedMensagensIndexRoute
  '/u/$username/amigos': typeof AuthenticatedUUsernameAmigosRoute
  '/u/$username/seguidores': typeof AuthenticatedUUsernameSeguidoresRoute
  '/u/$username/seguindo': typeof AuthenticatedUUsernameSeguindoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seguranca-adolescentes': typeof SegurancaAdolescentesRoute
  '/termos': typeof TermosRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app': typeof AuthenticatedAppRoute
  '/clips': typeof AuthenticatedClipsRoute
  '/explorar': typeof AuthenticatedExplorarRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/negocios': typeof AuthenticatedNegociosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/publicar': typeof AuthenticatedPublicarRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/negocios': typeof AdminNegociosRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/c/$slug': typeof CSlugRoute
  '/comunidades/nova': typeof ComunidadesNovaRoute
  '/help/account': typeof HelpAccountRoute
  '/help/ads': typeof HelpAdsRoute
  '/help/business': typeof HelpBusinessRoute
  '/help/chamados': typeof HelpChamadosRouteWithChildren
  '/help/community': typeof HelpCommunityRoute
  '/help/messages': typeof HelpMessagesRoute
  '/help/posts': typeof HelpPostsRoute
  '/help/security': typeof HelpSecurityRoute
  '/help/shop': typeof HelpShopRoute
  '/u/$username': typeof UUsernameRoute
  '/admin': typeof AdminIndexRoute
  '/comunidades': typeof ComunidadesIndexRoute
  '/configuracoes/perfil': typeof AuthenticatedConfiguracoesPerfilRoute
  '/mensagens/$id': typeof AuthenticatedMensagensIdRoute
  '/help/chamados/novo': typeof HelpChamadosNovoRoute
  '/mensagens': typeof AuthenticatedMensagensIndexRoute
  '/u/$username/amigos': typeof AuthenticatedUUsernameAmigosRoute
  '/u/$username/seguidores': typeof AuthenticatedUUsernameSeguidoresRoute
  '/u/$username/seguindo': typeof AuthenticatedUUsernameSeguindoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/help': typeof HelpRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seguranca-adolescentes': typeof SegurancaAdolescentesRoute
  '/termos': typeof TermosRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/clips': typeof AuthenticatedClipsRoute
  '/_authenticated/explorar': typeof AuthenticatedExplorarRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/negocios': typeof AuthenticatedNegociosRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/publicar': typeof AuthenticatedPublicarRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/negocios': typeof AdminNegociosRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/c/$slug': typeof CSlugRoute
  '/comunidades/nova': typeof ComunidadesNovaRoute
  '/help/account': typeof HelpAccountRoute
  '/help/ads': typeof HelpAdsRoute
  '/help/business': typeof HelpBusinessRoute
  '/help/chamados': typeof HelpChamadosRouteWithChildren
  '/help/community': typeof HelpCommunityRoute
  '/help/messages': typeof HelpMessagesRoute
  '/help/posts': typeof HelpPostsRoute
  '/help/security': typeof HelpSecurityRoute
  '/help/shop': typeof HelpShopRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/comunidades/': typeof ComunidadesIndexRoute
  '/_authenticated/configuracoes/perfil': typeof AuthenticatedConfiguracoesPerfilRoute
  '/_authenticated/mensagens/$id': typeof AuthenticatedMensagensIdRoute
  '/help/chamados/novo': typeof HelpChamadosNovoRoute
  '/_authenticated/mensagens/': typeof AuthenticatedMensagensIndexRoute
  '/_authenticated/u/$username/amigos': typeof AuthenticatedUUsernameAmigosRoute
  '/_authenticated/u/$username/seguidores': typeof AuthenticatedUUsernameSeguidoresRoute
  '/_authenticated/u/$username/seguindo': typeof AuthenticatedUUsernameSeguindoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/help'
    | '/privacidade'
    | '/reset-password'
    | '/seguranca-adolescentes'
    | '/termos'
    | '/verify-email'
    | '/app'
    | '/clips'
    | '/explorar'
    | '/feed'
    | '/negocios'
    | '/notificacoes'
    | '/publicar'
    | '/admin/denuncias'
    | '/admin/negocios'
    | '/admin/suporte'
    | '/c/$slug'
    | '/comunidades/nova'
    | '/help/account'
    | '/help/ads'
    | '/help/business'
    | '/help/chamados'
    | '/help/community'
    | '/help/messages'
    | '/help/posts'
    | '/help/security'
    | '/help/shop'
    | '/u/$username'
    | '/admin/'
    | '/comunidades/'
    | '/configuracoes/perfil'
    | '/mensagens/$id'
    | '/help/chamados/novo'
    | '/mensagens/'
    | '/u/$username/amigos'
    | '/u/$username/seguidores'
    | '/u/$username/seguindo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/help'
    | '/privacidade'
    | '/reset-password'
    | '/seguranca-adolescentes'
    | '/termos'
    | '/verify-email'
    | '/app'
    | '/clips'
    | '/explorar'
    | '/feed'
    | '/negocios'
    | '/notificacoes'
    | '/publicar'
    | '/admin/denuncias'
    | '/admin/negocios'
    | '/admin/suporte'
    | '/c/$slug'
    | '/comunidades/nova'
    | '/help/account'
    | '/help/ads'
    | '/help/business'
    | '/help/chamados'
    | '/help/community'
    | '/help/messages'
    | '/help/posts'
    | '/help/security'
    | '/help/shop'
    | '/u/$username'
    | '/admin'
    | '/comunidades'
    | '/configuracoes/perfil'
    | '/mensagens/$id'
    | '/help/chamados/novo'
    | '/mensagens'
    | '/u/$username/amigos'
    | '/u/$username/seguidores'
    | '/u/$username/seguindo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/help'
    | '/privacidade'
    | '/reset-password'
    | '/seguranca-adolescentes'
    | '/termos'
    | '/verify-email'
    | '/_authenticated/app'
    | '/_authenticated/clips'
    | '/_authenticated/explorar'
    | '/_authenticated/feed'
    | '/_authenticated/negocios'
    | '/_authenticated/notificacoes'
    | '/_authenticated/publicar'
    | '/admin/denuncias'
    | '/admin/negocios'
    | '/admin/suporte'
    | '/c/$slug'
    | '/comunidades/nova'
    | '/help/account'
    | '/help/ads'
    | '/help/business'
    | '/help/chamados'
    | '/help/community'
    | '/help/messages'
    | '/help/posts'
    | '/help/security'
    | '/help/shop'
    | '/u/$username'
    | '/admin/'
    | '/comunidades/'
    | '/_authenticated/configuracoes/perfil'
    | '/_authenticated/mensagens/$id'
    | '/help/chamados/novo'
    | '/_authenticated/mensagens/'
    | '/_authenticated/u/$username/amigos'
    | '/_authenticated/u/$username/seguidores'
    | '/_authenticated/u/$username/seguindo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HelpRoute: typeof HelpRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SegurancaAdolescentesRoute: typeof SegurancaAdolescentesRoute
  TermosRoute: typeof TermosRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminDenunciasRoute: typeof AdminDenunciasRoute
  AdminNegociosRoute: typeof AdminNegociosRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  CSlugRoute: typeof CSlugRoute
  ComunidadesNovaRoute: typeof ComunidadesNovaRoute
  UUsernameRoute: typeof UUsernameRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ComunidadesIndexRoute: typeof ComunidadesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca-adolescentes': {
      id: '/seguranca-adolescentes'
      path: '/seguranca-adolescentes'
      fullPath: '/seguranca-adolescentes'
      preLoaderRoute: typeof SegurancaAdolescentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clips': {
      id: '/_authenticated/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof AuthenticatedClipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explorar': {
      id: '/_authenticated/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof AuthenticatedExplorarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocios': {
      id: '/_authenticated/negocios'
      path: '/negocios'
      fullPath: '/negocios'
      preLoaderRoute: typeof AuthenticatedNegociosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publicar': {
      id: '/_authenticated/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof AuthenticatedPublicarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/denuncias': {
      id: '/admin/denuncias'
      path: '/admin/denuncias'
      fullPath: '/admin/denuncias'
      preLoaderRoute: typeof AdminDenunciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/negocios': {
      id: '/admin/negocios'
      path: '/admin/negocios'
      fullPath: '/admin/negocios'
      preLoaderRoute: typeof AdminNegociosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/admin/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidades/': {
      id: '/comunidades/'
      path: '/comunidades'
      fullPath: '/comunidades/'
      preLoaderRoute: typeof ComunidadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidades/nova': {
      id: '/comunidades/nova'
      path: '/comunidades/nova'
      fullPath: '/comunidades/nova'
      preLoaderRoute: typeof ComunidadesNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/account': {
      id: '/help/account'
      path: '/account'
      fullPath: '/help/account'
      preLoaderRoute: typeof HelpAccountRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/ads': {
      id: '/help/ads'
      path: '/ads'
      fullPath: '/help/ads'
      preLoaderRoute: typeof HelpAdsRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/business': {
      id: '/help/business'
      path: '/business'
      fullPath: '/help/business'
      preLoaderRoute: typeof HelpBusinessRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/chamados': {
      id: '/help/chamados'
      path: '/chamados'
      fullPath: '/help/chamados'
      preLoaderRoute: typeof HelpChamadosRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/community': {
      id: '/help/community'
      path: '/community'
      fullPath: '/help/community'
      preLoaderRoute: typeof HelpCommunityRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/messages': {
      id: '/help/messages'
      path: '/messages'
      fullPath: '/help/messages'
      preLoaderRoute: typeof HelpMessagesRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/posts': {
      id: '/help/posts'
      path: '/posts'
      fullPath: '/help/posts'
      preLoaderRoute: typeof HelpPostsRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/security': {
      id: '/help/security'
      path: '/security'
      fullPath: '/help/security'
      preLoaderRoute: typeof HelpSecurityRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/shop': {
      id: '/help/shop'
      path: '/shop'
      fullPath: '/help/shop'
      preLoaderRoute: typeof HelpShopRouteImport
      parentRoute: typeof HelpRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes/perfil': {
      id: '/_authenticated/configuracoes/perfil'
      path: '/configuracoes/perfil'
      fullPath: '/configuracoes/perfil'
      preLoaderRoute: typeof AuthenticatedConfiguracoesPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens/': {
      id: '/_authenticated/mensagens/'
      path: '/mensagens'
      fullPath: '/mensagens/'
      preLoaderRoute: typeof AuthenticatedMensagensIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens/$id': {
      id: '/_authenticated/mensagens/$id'
      path: '/mensagens/$id'
      fullPath: '/mensagens/$id'
      preLoaderRoute: typeof AuthenticatedMensagensIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/help/chamados/novo': {
      id: '/help/chamados/novo'
      path: '/novo'
      fullPath: '/help/chamados/novo'
      preLoaderRoute: typeof HelpChamadosNovoRouteImport
      parentRoute: typeof HelpChamadosRoute
    }
    '/_authenticated/u/$username/amigos': {
      id: '/_authenticated/u/$username/amigos'
      path: '/u/$username/amigos'
      fullPath: '/u/$username/amigos'
      preLoaderRoute: typeof AuthenticatedUUsernameAmigosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$username/seguidores': {
      id: '/_authenticated/u/$username/seguidores'
      path: '/u/$username/seguidores'
      fullPath: '/u/$username/seguidores'
      preLoaderRoute: typeof AuthenticatedUUsernameSeguidoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$username/seguindo': {
      id: '/_authenticated/u/$username/seguindo'
      path: '/u/$username/seguindo'
      fullPath: '/u/$username/seguindo'
      preLoaderRoute: typeof AuthenticatedUUsernameSeguindoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedClipsRoute: typeof AuthenticatedClipsRoute
  AuthenticatedExplorarRoute: typeof AuthenticatedExplorarRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedNegociosRoute: typeof AuthenticatedNegociosRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPublicarRoute: typeof AuthenticatedPublicarRoute
  AuthenticatedConfiguracoesPerfilRoute: typeof AuthenticatedConfiguracoesPerfilRoute
  AuthenticatedMensagensIdRoute: typeof AuthenticatedMensagensIdRoute
  AuthenticatedMensagensIndexRoute: typeof AuthenticatedMensagensIndexRoute
  AuthenticatedUUsernameAmigosRoute: typeof AuthenticatedUUsernameAmigosRoute
  AuthenticatedUUsernameSeguidoresRoute: typeof AuthenticatedUUsernameSeguidoresRoute
  AuthenticatedUUsernameSeguindoRoute: typeof AuthenticatedUUsernameSeguindoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedClipsRoute: AuthenticatedClipsRoute,
  AuthenticatedExplorarRoute: AuthenticatedExplorarRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedNegociosRoute: AuthenticatedNegociosRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPublicarRoute: AuthenticatedPublicarRoute,
  AuthenticatedConfiguracoesPerfilRoute: AuthenticatedConfiguracoesPerfilRoute,
  AuthenticatedMensagensIdRoute: AuthenticatedMensagensIdRoute,
  AuthenticatedMensagensIndexRoute: AuthenticatedMensagensIndexRoute,
  AuthenticatedUUsernameAmigosRoute: AuthenticatedUUsernameAmigosRoute,
  AuthenticatedUUsernameSeguidoresRoute: AuthenticatedUUsernameSeguidoresRoute,
  AuthenticatedUUsernameSeguindoRoute: AuthenticatedUUsernameSeguindoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface HelpChamadosRouteChildren {
  HelpChamadosNovoRoute: typeof HelpChamadosNovoRoute
}

const HelpChamadosRouteChildren: HelpChamadosRouteChildren = {
  HelpChamadosNovoRoute: HelpChamadosNovoRoute,
}

const HelpChamadosRouteWithChildren = HelpChamadosRoute._addFileChildren(
  HelpChamadosRouteChildren,
)

interface HelpRouteChildren {
  HelpAccountRoute: typeof HelpAccountRoute
  HelpAdsRoute: typeof HelpAdsRoute
  HelpBusinessRoute: typeof HelpBusinessRoute
  HelpChamadosRoute: typeof HelpChamadosRouteWithChildren
  HelpCommunityRoute: typeof HelpCommunityRoute
  HelpMessagesRoute: typeof HelpMessagesRoute
  HelpPostsRoute: typeof HelpPostsRoute
  HelpSecurityRoute: typeof HelpSecurityRoute
  HelpShopRoute: typeof HelpShopRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpAccountRoute: HelpAccountRoute,
  HelpAdsRoute: HelpAdsRoute,
  HelpBusinessRoute: HelpBusinessRoute,
  HelpChamadosRoute: HelpChamadosRouteWithChildren,
  HelpCommunityRoute: HelpCommunityRoute,
  HelpMessagesRoute: HelpMessagesRoute,
  HelpPostsRoute: HelpPostsRoute,
  HelpSecurityRoute: HelpSecurityRoute,
  HelpShopRoute: HelpShopRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HelpRoute: HelpRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SegurancaAdolescentesRoute: SegurancaAdolescentesRoute,
  TermosRoute: TermosRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminDenunciasRoute: AdminDenunciasRoute,
  AdminNegociosRoute: AdminNegociosRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  CSlugRoute: CSlugRoute,
  ComunidadesNovaRoute: ComunidadesNovaRoute,
  UUsernameRoute: UUsernameRoute,
  AdminIndexRoute: AdminIndexRoute,
  ComunidadesIndexRoute: ComunidadesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
